# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
